### ISSUE TITLE
rqt_bag: Implement Horizontal Overview section

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt_common_plugins#11]
Currently horizontal scrolling is painful in rqt_bag. The main way being middle mouse dragging.

A good improvement would be a visualization of the entire bag across the top of the graphicsview. 
It should allow for clicking to jump to any point in the bag file.
It should show the current viewport position on the entire visualization.
If you click the viewport and drag it then the viewport should re-position to the desired location.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_bag#2
