### ISSUE TITLE
rqt_logger_level takes too long to start up / refresh

### ISSUE THREAD

**Issue by tkruse** [ros-visualization/rqt_common_plugins#147]
On my machine, with a reasonable number of nodes running on a remote PR2, rxloggerlevel takes about 6 seconds too start, rqt_logger_level about 12. Similarly a refresh in rxloggerlevel takes 3 secs, rqt_loggerlevel 12 again.

Since they do roughly the same, I assume that is a bug in rqt_loggerlevel. Probably you won't notice if the nodes are running locally or just a few nodes.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_logger_level#3
