### ISSUE TITLE
rqt_reconfigure) picks up parameters only upon its booting

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_common_plugins#154]
A work-around [is documented](http://www.ros.org/wiki/rqt_reconfigure#Limitation).

**Comment by 130s** [comment]
Closing since I guess this was addressed in https://github.com/ros-visualization/rqt_common_plugins/pull/319.

**Comment by zimonitrome** [comment]
I think this feature could still be useful.

Forgive me for my unawareness of how rqt_reconfigure works but I have seen one parameter change update another parameter in the RQT GUI when calling set_parameter inside the parameter callback.

Also is this repo still active or does https://github.com/ros-visualization/rqt contain updated plugins?

**Comment by MatthijsBurgh** [comment]
This is just a metapackage.

The plugins have their own repo. The `rqt` repo contains all the core code. No plugins.

Also this issue has been closed for more than 6 years. So please open a new issue and refer to this one.
