### ISSUE TITLE
rqt_reconfigure: After filtering, node selection gets reset even though some nodes were selected

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_common_plugins#18]
**Possible bad situation**: node boxes are shown on right-hand side but their item on left-hand is not selected. When user selects a node on LH, the corresponding box disappears from RH.

---

I described the problematic [phenomenon in the question on stackoverflow](http://stackoverflow.com/questions/14551580/not-qitemselectionmodel-selectionchanged-called-when-using-qsortfilterproxymodel) (satisfactory responses from there can help solving this issue too).

Related to issue #17.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_reconfigure#1
