### ISSUE TITLE
rqt_plot: (matplot only) shows strange output after running for ~5 minutes (progressively gets worse)

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt_common_plugins#19]
Migrated from https://github.com/ros-visualization/rqt/issues/48

---

The issue:![snapshot14](https://f.cloud.github.com/assets/2374428/4739/ca0814d2-431f-11e2-84a6-a7f1dfe59dc4.png)

steps to duplicate
execute the UnderstandingTopics tutorial (http://www.ros.org/wiki/ROS/Tutorials/UnderstandingTopics)
leave the rqt_plot open for an extended period of time.
You will see the following:
![after](https://f.cloud.github.com/assets/2374428/4776/df579af4-4321-11e2-997d-bc8c5d1fda9f.png)

It should look like the following (it starts this way and progressively gets worse:
![before1](https://f.cloud.github.com/assets/2374428/4782/33dcb488-4322-11e2-966d-a1a430b8ac7f.png)

groovy
using rqt 1.5

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_plot#1
