### ISSUE TITLE
rqt_console: "Fit Columns" button cannot be easily undone / has a counter-intuitive name

### ISSUE THREAD

**Issue by jbohren** [ros-visualization/rqt_common_plugins#195]
In rqt_console, there is a "Fit Columns" button, which expands all the columns so that their contents isn't truncated. I propose that "Fit Columns" should be renamed to a toggle button "Expand Columns" and an additional, mutually-exclusive toggle button should be added which causes the columns to fit within the window as it gets resized.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_console#2
