### ISSUE TITLE
Multi-robot teleoperator

### ISSUE THREAD

**Issue by blackpc** [ros-visualization/rqt_common_plugins#199]
We are developing a rqt plugin to control multiple robots using a joystick (Xbox, PS) and are open for ideas or requests

**Comment by ablasdel** [comment]
@dirk-thomas @TomySela @blackpc @cogniteam  I just had the current version of https://github.com/cogniteam/mr_teleoperator demoed to me by one of our interns. This is so much better than "robot_steering" it is almost laughable.

If you guys are still willing to have this merged into the main line I would suggest we remove robot steering and replace it with this tool. 

One thing though I would prefer we change the name to something like rqt_teleop, rqt_robot_steering or something similar.

**Comment by dirk-thomas** [comment]
We don't necessarily have to pull in all good rqt plugin into a single repository. That makes it more difficult to maintain / release / spread the load. Renaming the package to something like `rqt_teleop` sound reasonable. It could also be considered to be included in one of the default metapackages like `desktop` (http://www.ros.org/reps/rep-0142.html).

`rqt_robot_steering` was the very first rqt plugin written at a workshop in a few hours to show a simple graphical user interface. Keeping it or removing it should be an independent decision.

**Comment by ablasdel** [comment]
That makes sense. I will take a look at all of the mr_tools and see if we can just pull in the whole set of them. From my experiance with mr_teleop I think they are a good candidate for inclusion in the default install.

On an unrelated note: I think rqt_robot_steering should be deleted unless we are going to improve it. The latching behavior of the sliders can create dangerous robot situations.

**Comment by ablasdel** [comment]
I opened some tickets on the github about releasing for indigo/jade and they haven't been replied to in ~ 1.5 months. I am going to close this until we get a reply. Can reopen then.

**Comment by k-okada** [comment]
FYI. I tried https://github.com/aquahika/rqt_virtual_joystick/ and works fine.
