### ISSUE TITLE
rqt_plot loses configuration on startup

### ISSUE THREAD

**Issue by trainman419** [ros-visualization/rqt_common_plugins#229]
When starting up, if rqt_plot can't find a topic, it silently ignores it and removes it from the configuration. This causes two problems:
- If you try to rely on the RQT framework to persist your plotting settings, they will silently be removed if the publisher isn't active when rqt_plot restarts
- If you start rqt_plot with a list of topics, any topics from the command line that don't exist are silently ignored

Note that any solution to this should also be aware of the changes that were made to fix #110 

It might be worth trying:
- Maintaining internal configuration even if topics don't exist - possibly including topic types
- Not blocking startup on missing topics
- occasionally polling to see if missing topics have appeared
- failing startup if topics/fields specified on the command line don't exist

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_plot#4
