### ISSUE TITLE
rqt_logger_level: Save and restore logger levels & multi process level setting

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt_common_plugins#23]
moved from https://github.com/ros-visualization/rqt/issues/52

---

Redesign the plugin to allow block selecting so you can set the logger level of multiple processes at the same time.

implement a save/load from a file OR implement the rqt save/restore functionality.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_logger_level#2
