### ISSUE TITLE
ROS Package Graph

### ISSUE THREAD

**Issue by posilva** [ros-visualization/rqt_common_plugins#249]
Hi,

I'm trying to create a package dependency graph with rqt "Package Graph" Plugin, and something is missing here. I have a x_autopilot_msg  that depends on x_commons_msgs and when I run the plugin I cannot see this dependency? 

I have a x_commons package that other packages depends on, but in the graph I cannot see x_commons with all this packages that depends on him.

This is an example of a [graph](http://snag.gy/l3AY3.jpg) where autopilot depends on commons (as you can see in the [package.xml](https://gist.github.com/posilva/13e90e6e7f6c11eddb64))

Thanks 

pms

![autopilot_commons_dependecy_missing_graph](https://cloud.githubusercontent.com/assets/1260664/3358258/16214d0a-fadc-11e3-90f9-621a23503580.png)

**Comment by dirk-thomas** [comment]
I will close this ticket due to no response. Please feel free to continue commenting with more information and the issue can be reopened.
