### ISSUE TITLE
rqt_bag: rqt_bag plugin not found on Ubuntu 14.04 LTS with Indigo

### ISSUE THREAD

**Issue by venabled** [ros-visualization/rqt_common_plugins#255]
I have the 0.3.6 release of ros-indigo-rqt-bag, ros-indigo-rqt-bag-plugins installed: 

```
venabled@tesla:~$ sudo apt list *rqt-bag*
Listing... Done
ros-indigo-rqt-bag/trusty,now 0.3.6-0trusty-20140629-1853-+0000 amd64 [installed]
ros-indigo-rqt-bag-plugins/trusty,now 0.3.6-0trusty-20140629-1855-+0000 amd64 [installed]
```

And when I run rqt_bag from the command line, qt_gui_main() can't find the rqt_bag plugin: 

```
venabled@tesla:~$ rqt_bag
qt_gui_main() found no plugin matching "rqt_bag"
```

**Comment by elliotjo** [comment]
I ran into this problem today on two separate workstations with fresh installs of Linux Mint 17.2 running Indigo.  For anyone else who has this issue, I was able to resolve it by deleting .config/ros.org/rqt_gui.ini.  I think there may still be a problem with how the plugins are cached.

**Comment by Jonksar** [comment]
My install was all kinds of screw'd up but managed to follow @elliotjo advice which fixed it for me. Seems like a minor fix somewhere.

**Comment by sudo-robot-destroy** [comment]
I had the same problem only I couldn't get rqt_controller_manager to run, deleting rqt_gui.ini fixed things for me as well.
