### ISSUE TITLE
rqt_image_view: display frame-rate and bandwidth

### ISSUE THREAD

**Issue by Carter12s** [ros-visualization/rqt_common_plugins#258]
It would be very useful for debugging purposes and development to have the Framerate and approximate data throughput of an image stream displayable with the stream in rqt_image_view

**Comment by martonmiklos** [comment]
Hello all,

I have started to work on something similar:
I am patching the rqt_image_view to be able to subscribe to an another image topic where an ARGB image should be published. Using this method you could create an own overlayer node to add  informations to the screen as you want. (Fake horizont, speed info, whatever).

I have also added a latency bar which would draw a bar to the top to display the difference between the timestamp in the image header to the current (drawing time):
![inf1](https://cloud.githubusercontent.com/assets/1609182/14300055/36bed186-fb8e-11e5-9b12-7c72fd4215c7.png)

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_image_view#1
