### ISSUE TITLE
Plot plugin: add/remove, pause/resume individual topics  (ros-pkg ticket #5471)

### ISSUE THREAD

**Issue by tfoote** [ros-visualization/rqt_common_plugins#27]
Plot plugin:
- [ ] add/remove individual topics
- [ ] pause/resume individual topics
- [ ] persist/restore list of topics via settings
- [x] auto-complete topic name (?)
- [ ] clear-plot button

trac data:
- Owner: **dorianscholz**
- Reporter: **dthomas**
- Reported at: **Wed Jun 20 19:31:06 2012**
- URL: https://code.ros.org/trac/ros-pkg/ticket/5471

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_plot#2
