### ISSUE TITLE
ServiceCaller plugin: multiple requests  (ros-pkg ticket #5472)

### ISSUE THREAD

**Issue by tfoote** [ros-visualization/rqt_common_plugins#28]
ServiceCaller plugin:
- add requests to a list (like in the Publisher)
- call them "on click"/"on context menu"
- persist/restore list of requests with their expressions
- show response below list of request to reduce horizontal space consumption

trac data:
- Owner: **dorianscholz**
- Reporter: **dthomas**
- Reported at: **Wed Jun 20 19:35:21 2012**
- URL: https://code.ros.org/trac/ros-pkg/ticket/5472

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_service_caller#1
