### ISSUE TITLE
rqt_graph: More Topic Grouping support

### ISSUE THREAD

**Issue by mitchellwills** [ros-visualization/rqt_common_plugins#282]
Right now when viewing a node graph with image topics there are a lot of extra topics (when not hiding leafs and dead sinks). Specifically it may make sense to treat dynamic reconfigure topics (parameter_updates and parameter_descriptions) as debug topics. Also grouping the actual image transport topics like action topics are currently grouped would also complicate the node/topic graphs a lot. For a single image stream (with a corresponding image_proc node) there are a total of 57 topics (with the raw, compressed, compressed Depth, and theora transports installed). Of those 36 of them are for dynamic reconfigure. If those were hidden as debug parameters then there are 21 topics with actual image information. As there are 5 different image streams the 21 topics could be reduced to a total of 6 topics (camera_info and 5 image_transport topics). Additionally these 6 topics could be essentially be merged down into one combined topic as they are variations on the same data.

This could be implemented by adding a drop down for image transport grouping for either no grouping, grouping of different transport types, or grouping of all processed versions of an image.

Also it may be nice to distinguish grouped topics with a different symbol (maybe a set of stacked rectangles) to make it clearer that it is a group (such as http://i.stack.imgur.com/QzxoV.png).

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_graph#3
