### ISSUE TITLE
rqt_top: Restarted nodes do not reappear

### ISSUE THREAD

**Issue by odel4y** [ros-visualization/rqt_common_plugins#294]
The process monitor plugin fails to redisplay nodes that have been killed and restarted while it is running. The cause seems to be in [node_info.py](https://github.com/ros-visualization/rqt_common_plugins/blob/groovy-devel/rqt_top/src/rqt_top/node_info.py):

* Nodes that are killed during runtime do not get removed from `self.nodes`. A solution would be to define a method to check for obsolete nodes like so:
```python
def remove_dead_nodes(self):
    running_nodes = rosnode.get_node_names()
    dead_nodes = [node_name for node_name in self.nodes if node_name not in running_nodes]
    for node_name in dead_nodes:
        self.nodes.pop(node_name, None)
```
and call that method in every `get_all_node_info()`

* Restarted nodes change their uri but the module rosnode does not automatically reflect that change in its cached `rosnode.get_api_uri()` call. In the following the process monitor is unable to find the restarted process and does not display it.
I would suggest to rebuild that cache in case of error like so:
```python
def get_node_info(self, node_name, skip_cache=False):
    node_api = rosnode.get_api_uri(rospy.get_master(), node_name, skip_cache=skip_cache)
    try:
        code, msg, pid = xmlrpclib.ServerProxy(node_api[2]).getPid(ID)
        if node_name in self.nodes:
            return self.nodes[node_name]
        else:
            try:
                p = psutil.Process(pid)
                self.nodes[node_name] = p
                return p
            except:
                return False
    except xmlrpclib.socket.error,e:
        if not skip_cache:
            return self.get_node_info(node_name, skip_cache=True)
        else:
            return False
```

**Comment by ablasdel** [comment]
merge of #295 fixed this
