### ISSUE TITLE
rqt_shell: run a command on load and continue

### ISSUE THREAD

**Issue by kunaltyagi** [ros-visualization/rqt_common_plugins#296]
Most of the time, while using rqt_shell, it is preferred to run a script, such as setting env variables for remote ROS_MASTER. Instead of manually running them, it would be nice to have an option to pass a script to rqt_shell which it would run.
Currently, it uses `/usr/bin/xterm`, without arguments, instead if we use `/usr/bin/xterm -e "absolute_path_to_executable_script; $SHELL"` we can achieve the requirements.
On the user end, it is easy to give absolute path prefix by using `rospack.getpath` and appending the relative path from the package root it it.

This holds true only for xterm_widget. I don't know how to make a similar change in the other two widgets  (is it even required?)

**Comment by ablasdel** [comment]
I like the idea of this feature and if you (or anyone) have the time to code it up I would be willing to take some time to review/merge it in.

**Comment by kunaltyagi** [comment]
I did make a tiny amount of change in xterm_widget.py, not sure how to propagate it till user level

**Comment by ablasdel** [comment]
https://github.com/ros-visualization/rqt_common_plugins/pull/298 is a good start.

Next steps would be:

1 Give a similar interface (pass in the script path) to the other 2 shell classes (SpyderShellWidget and ShellWidget) so there is a common interface.

2 Parse the command line and pass it into the selected widget when it is created here:
```
https://github.com/ros-visualization/rqt_common_plugins/blob/groovy-devel/rqt_shell/src/rqt_shell/shell.py#L98
```
Argparse example:
```
https://github.com/ros-visualization/rqt_common_plugins/blob/cbef6423ad89a83387bfe615678cf9693e313e9c/rqt_bag/src/rqt_bag/bag.py#L67
```

**Comment by kunaltyagi** [comment]
Couldn't understand how shell_widget.py runs a command. Updated the other two widgets to handle changes in env var also

**Comment by ablasdel** [comment]
My bad that is just a base class to ensure the ui gets loaded. With that in mind the changes you made to #298  fulfill step 1 and look good.

Once there is argparse integration I can test this this out and evaluate it.

**Comment by kunaltyagi** [comment]
The latest commit should suffice in that case. I also made a change in the way the script is run to allow the script to be able to set env vars too.

**Comment by ablasdel** [comment]
That looks good. I will test this out next week.
Could you squash the commits into one?

**Comment by ablasdel** [comment]
@kunaltyagi I'm unassigning myself due to not actively working on getting this merged in. When you have it working please @ me and I will pick it back up again.

**Comment by iRapha** [comment]
Have there been any updates on this issue?

**Comment by kunaltyagi** [comment]
I totally forgot about this. Lemme see where I left this. Should have the code on one of my old hard drives ( :fearful:)
