### ISSUE TITLE
(rqt_console) (nice-to-have) move filtering classes to common pkgs

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_common_plugins#30]
I know it wasn't intended when `rqt_console` was initially written to make all those filter classes to be generic. But it would be very beneficial to have a set of filtering components that provide multiple types of filters and users can select / de-select them on GUI while system aggregates the result from all selected filters (like `rqt_console` does).

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_console#1
