### ISSUE TITLE
rqt_bag: plot view becomes corrupt/duplicated when closing and reopening

### ISSUE THREAD

**Issue by trainman419** [ros-visualization/rqt_common_plugins#309]
Found when testing and reviewing #306 and #307:

If I open a plot view for a topic, close it, and reopen it, the plot view now contains two copies of every UI element.

I suspect this is because the layout isn't properly cleared out when the Widget is reopened, and in the past this has been masked by #306.

**Comment by trainman419** [comment]
This also happens for raw views if #306 is fixed (per #307).

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_bag#5
