### ISSUE TITLE
rqt_bag: plot plugin only lets you plot 1 topic

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt_common_plugins#312]
It would be nice if you could get multiple topics in the same plugin graph for correlation.

**Comment by trainman419** [comment]
The best way to do this would be through the same context menu that allows plotting: instead of just offering to plot a topic, the menu should also allow the user to add the selected topic to an existing plot.

**Comment by ablasdel** [comment]
I like that. All we would have to do is give each of the port windows a unique title and display that as an option in the drop down. This actually doesn't sound super hard at all. If I get some time next week I will see if I can implement this before I release rqt.

**Comment by ablasdel** [comment]
Coming up on the self assign anniversary... It is pretty clear other priorities won out. If that looks like it will change I will reassign myself.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_bag#7
