### ISSUE TITLE
Release rqt_common_plugins 0.3.12

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt_common_plugins#329]
- [x] Rename master branch
- [x] update tracks files with new master branch!
- [x] Release 0.3.12 for Indigo & Jade

**Comment by ablasdel** [comment]
@dirk-thomas This one actually has some fixes for hydro. Do you think I should release or leave off?
I'm going to look over each commit but I think you probably should too if we are doing hydro here.

**Comment by dirk-thomas** [comment]
Your call :wink: If the changes don't pose a high risk for regressions (e.g. a syntax error) you can do a hydro release if it makes sense to make these changes available.

**Comment by ablasdel** [comment]
Roger. I have tested all but the rqt_reconfigure personally. @cottsay can you vouch for the rqt_reconfigure changes since the last release? No regressions have become evident right?
