### ISSUE TITLE
rqt_bag: Requires core to be open just to examine bag file

### ISSUE THREAD

**Issue by DLu** [ros-visualization/rqt_common_plugins#332]
I believe with rxbag you could just open bag files to examine them without a core. However, rqt_bag requires a core, even without trying to publish anything.

**Comment by dirk-thomas** [comment]
In rqt the type of a plugin determines if it requires a ROS node or not. The infrastructure currently does not allow to start as non-ROS-node-plugin and then request a ROS node afterwards. Therefore it is currently not possible to implement the requested feature in a single plugin.

I would be possible though to refactor rqt_bag into two plugins: one which does not allow to publish and one with the current functionality. Not a nice approach though.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_bag#9
