### ISSUE TITLE
rqt_graph: Incorrect Display with node that has the same name as a topic

### ISSUE THREAD

**Issue by DLu** [ros-visualization/rqt_common_plugins#333]
<launch>
        <node name="tf1" pkg="tf" type="static_transform_publisher" args="0 0 0 0 0 0 /a /b 100" />
    </launch>

Run this with rqt_graph (nodes and messages), and it correctly shows a node named tf1 and a topic named tf. 
![Screenshot](http://i.imgur.com/oPdsAOj.png)

Change the name of the node...

    <launch>
        <node name="tf" pkg="tf" type="static_transform_publisher" args="0 0 0 0 0 0 /a /b 100" />
    </launch>

Now it displays just a single node with an arrow that points at itself. 
![Screenshot](http://i.imgur.com/KNIq6Ai.png)

**Comment by eric-wieser** [comment]
This is because dot nodes are identified by name, and the default name is the same as the text contents.

I think the fix goes somewhere in https://github.com/ros-visualization/rqt_common_plugins/blob/master/rqt_graph/src/rqt_graph/dotcode.py
