### ISSUE TITLE
rqt_graph: Option to group/ignore dynamic_reconfigure topics

### ISSUE THREAD

**Issue by DLu** [ros-visualization/rqt_common_plugins#334]
All my graphs are cluttered with ~parameter_descriptions and ~parameter_updates.

**Comment by FrostHand** [comment]
You can add filter, some sort of: -(.*parameter_updates),-(.*parameter_descriptions)

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_graph#4
