### ISSUE TITLE
rqt_top: Incorrect urls in manifest

### ISSUE THREAD

**Issue by DLu** [ros-visualization/rqt_common_plugins#335]
@dlaz

**Comment by dlaz** [comment]
You just had to make me write a script for this, didn't you? See #337.

**Comment by DLu** [comment]
What did your script look like and should we integrate it into roscompile?

**Comment by dlaz** [comment]
https://gist.github.com/dlaz/a52b7387e743e8a92ac6

If you want to integrate it into roscompile, I can flesh it out a bit and submit a PR.
