### ISSUE TITLE
rqt_py_common: Standardized ROS message selector interface

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt_common_plugins#34]
A number of plugins want to refer to `topic`/`services`/`action`s.

It would be nice to have a widget in rqt_py_common that any plugin could easily use to select one of these items.

examples of ways it has been done:
rqt_msg, rqt_srv, rqt_action, rqt_publish, rqt_graph

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt#119
