### ISSUE TITLE
rqt_top: update required for new psutil API

### ISSUE THREAD

**Issue by bchretien** [ros-visualization/rqt_common_plugins#349]
I got the following error with psutil 3.3.0 on Arch Linux:

```txt
  File "/opt/ros/indigo/lib/python2.7/site-packages/rqt_top/node_info.py", line 69, in get_all_node_fields
    infos.append(self.as_dict(p, fields + ['cmdline', 'get_memory_info']))
  File "/opt/ros/indigo/lib/python2.7/site-packages/rqt_top/node_info.py", line 97, in as_dict
    attr = getattr(p, name)
AttributeError: 'Process' object has no attribute 'get_memory_info'
```
Apparently `get_memory_info`, `get_children`, `get_num_threads` and other `get_*` methods were renamed in the 2.2.0 release of 2014-03-10 (see the [changelog](https://github.com/giampaolo/psutil/blob/master/HISTORY.rst)).

**Comment by dirk-thomas** [comment]
This should already be fixed since ad5a8112d94c6ebc2fcb954beec85613170cc607. If not please comment and the ticket can be reopened.
