### ISSUE TITLE
rqt_image_view needs run depends on qtbase5-dev

### ISSUE THREAD

**Issue by tfoote** [ros-visualization/rqt_common_plugins#371]
This is the same problem as https://github.com/ros-visualization/rqt_robot_plugins/issues/102 breaking the build on debian jessie. 

http://build.ros.org:8080/view/Kbin_dJ64/job/Kbin_dJ64__rqt_image_view__debian_jessie_amd64__binary/9/consoleFull

**Comment by dirk-thomas** [comment]
See https://github.com/ros-visualization/rqt_robot_plugins/issues/102#issuecomment-216714781
