### ISSUE TITLE
rqt_graph text labels for nodes and topics seem too large in kinetic/Xenial

### ISSUE THREAD

**Issue by kengregson** [ros-visualization/rqt_common_plugins#375]
png image attached

![rqt_graph__rosgraph - rqt_001](https://cloud.githubusercontent.com/assets/1144342/15201689/9abc96a6-17c1-11e6-9806-e9b397ab4ac4.png)

**Comment by dirk-thomas** [comment]
This is likely unrelated to Kinetic / Xenial - I would expect you to see the same on Indigo / Trusty - especially since the plugin uses the same code for both. I can reproduce the problem on a system which has a high resolution monitor which uses a factor of around 2 for "Scale for menus and title bars". Can you confirm that you have configure a system wide scaling factor on your system?

**Comment by dirk-thomas** [comment]
The only workaround I am currently aware of is setting `QT_DEVICE_PIXEL_RATIO=2` in your environment before starting `rqt_graph`. Can you please try that and comment with the result.

**Comment by kengregson** [comment]
Yes, 14" QXD+ display on a Razer Blade with system scale factor set to
1.5x.  Good catch, I'll check with 1x to confirm.

This is likely unrelated to Kinetic / Xenial - I would expect you to see
the same on Indigo / Trusty - especially since the plugin uses the same
code for both. I can reproduce the problem on a system which has a high
resolution monitor which uses a factor of around 2 for "Scale for menus and
title bars". Can you confirm that you have configure a system wide scaling
factor on your system?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/ros-visualization/rqt_common_plugins/issues/375#issuecomment-218885532>

**Comment by kengregson** [comment]
Confirmed QT_DEVICE_PIXEL_RATIO=2 scales rqt_graph text as desired (with system wide scaling factor set to 1.5 for high resolution monitor).  Before and after attached.  Thanks!
![rqt_graph__rosgraph - rqt_001](https://cloud.githubusercontent.com/assets/1144342/15266364/575003b6-1970-11e6-9d86-4569b7cfbffb.png)
![rqt_graph__rosgraph - rqt_002](https://cloud.githubusercontent.com/assets/1144342/15266365/5750f8a2-1970-11e6-900d-29e1408ac9aa.png)
