### ISSUE TITLE
Generic UI plugin for rqt?

### ISSUE THREAD

**Issue by martonmiklos** [ros-visualization/rqt_common_plugins#377]
Hello all,

I have opened this issue to do some brainstorming before start implementing a new plugin.

Problem: I often find manipulating/monitoring topics with the Topic monitor and the Message publisher plugin no so intuitive. For e.g. when adjusting something servo driven mechanical structure using a knob widget is more easy and straightforward than typing in a number to the Message publisher. Also visualizing a position of something sometimes more handful with a dial/slider. Building a separate plugin each time is a little bit problematic.

Proposal: I would like to create a plugin which would have a file browse input and an interval spinbox (ms). I think the Qt Designer is a pretty good tool to create user interfaces pretty quickly. The plugin would be able to load the designed ui files. The Qt has a QUiLoader class to acheieve this functionality:http://doc.qt.io/qt-4.8/quiloader.html In Qt designer it is possible to add further properties to the widgets. There would be two dedicated property names: the publish_topic and the subscribe_topic. The widget tree would be traversed by recursively iterating through the children() method and if one of these properties found the widget would be connected to ros through the proper signals/slots. The proper slots/signals are dependent on the widget class, so some QMetaObject magic will be required, but it can be implemented.

If you have any ideas recommendations please let me know!

Thanks in advance!

**Comment by dirk-thomas** [comment]
Since this is a question I think you post on answers.ros.org is sufficient: http://answers.ros.org/question/234379/generic-ui-plugin-for-rqt/
