### ISSUE TITLE
Filter service call list in rqt_service_caller

### ISSUE THREAD

**Issue by felixendres** [ros-visualization/rqt_common_plugins#386]
It would be great if rqt_service_caller would not always list all available service calls (including all the logging related ones), but just specific ones. One could filter them, e.g. with a regexp, or via selecting a specific namespace.

My current, somewhat unsatisfactory workaround is to remap the name of the service I am interested in, so it appears first in the alphabetically ordered dropdown menu.

**Comment by dirk-thomas** [comment]
That sounds like a good improvement. Please consider to contribute a pull request which adds such a filter to the plugin.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_service_caller#2
