### ISSUE TITLE
rqt_plot should have setting to turn off y-axis autoscale

### ISSUE THREAD

**Issue by peter-moran** [ros-visualization/rqt_common_plugins#392]
Autoscale is an awesome feature in rqt_plot, however sometimes I really wish I could fix the y axes and focus on one range of values.

This is especially true when I'm dealing with data that has large outliers. Every time an outlier comes in, the plot zooms out so much that I have to rescale my plot to see the usual data.

see: http://answers.ros.org/question/209492/rqt_plot-fixed-y-axis-limits/

**Comment by dirk-thomas** [comment]
This sounds like a great feature. Please consider to contribute a pull request adding such an option to the plugin.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_plot#6
