### ISSUE TITLE
How can I see bag file

### ISSUE THREAD

**Issue by romdos** [ros-visualization/rqt_common_plugins#395]
I suppose that bag file of http://vision.in.tum.de/data/datasets/rgbd-dataset/download dataset can be visualized, i.e I can watch it like a video. I run next commands, but nothing changes:
>roscore
(new terminal)
> rqt_bag  example.bag
![rqt](https://cloud.githubusercontent.com/assets/15799418/17459432/f1bda978-5c3f-11e6-888e-05af201503b6.png)

**Comment by dirk-thomas** [comment]
Please ask questions one http://answers.ros.org. You can right-click any topic and enabling publishing the messages (and visualize them in other tools) or view some known times directly within this plugin.
