### ISSUE TITLE
rqt_launch: remote launch

### ISSUE THREAD

**Issue by houlei516** [ros-visualization/rqt_common_plugins#405]
I would like to launch individual launch file from rqt_launch to teleoperate my robot which has several odroid chip on board, but unsuccessful. Our individual launch file follow this syntax and work well in Ubuntu terminal. http://wiki.ros.org/roslaunch/XML/machine 
Of course the main launch file is also run outside GUI, but on Ubuntu terminal.  

  In ourselves rqt plug-in by Python, the remote launch can be realized by 
  self._widget.Laser.clicked.connect(self.LaserCommand)
...
  def LaserCommand(self):
        self._widget.Laser.setEnabled(False)
        subprocess.Popen(["roslaunch", "spir_master", "bringUpLaserRangeFinder.launch"])
  ...
But we cannot easily find out how to stop it, not to mention the self plugin is too simple. 
  How to modify the corresponding code of rqt_launch by adding the bash shell command like subpress.Popen and stop launch files? Thank you.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_launch#14
