### ISSUE TITLE
pyqtgraph disabled

### ISSUE THREAD

**Issue by rangsjo** [ros-visualization/rqt_common_plugins#407]
Hi,
could this commit: 
**disable PyQtGraph backend when Qt 5 is being used #399**
 be reverted since pyqtgraph 0.10.0 supports qt5?

After rolling back to rqt_plot 0.4.1 and use pyqtgraph 0.10.0 I am able to use pyqtgraph in rqt_plot in ubuntu 16.04 with ros kinetic.

**Comment by dirk-thomas** [comment]
Can you please try the code from #415 and confirm that it works for you.

**Comment by rangsjo** [comment]
I can confirm that this fix solves my problem.
Thanks!

**Comment by dirk-thomas** [comment]
Thank you for checking.
