### ISSUE TITLE
(new plugin idea) GPS plotter

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_common_plugins#41]
Plot GPS msgs on real-world map realtime. Message format can be:
- [sensor_msgs/NavSatStatus](http://ros.org/doc/api/sensor_msgs/html/msg/NavSatStatus.html) and [sensor_msgs/NavSatFix](http://ros.org/doc/api/sensor_msgs/html/msg/NavSatFix.html)
- [gps_comm](http://www.ros.org/wiki/gps_common)

(looks like the ones in `sensor_msgs` are official?)

Opinions (esp. is this going to be useful or not. If useful then what features are needed) are welcomed.

This idea is tech-driven -- I found Qt-Google API client. http://www.ics.com/technologies/qt_google_apis/. I'm asking the company about license, which is missing in their downloadable. But we're open to any possible technology.

Google Earth might be also possible by using [its API](http://stackoverflow.com/questions/9740982/qt-and-google-earth-api).

Note that a single `rqt` plugin should better be minimal -- for example, integrating with other large tool like `RViz` should be considered as separate plugin (as `rqt_pr2_dashboard` does)).

**Comment by vincentrou** [comment]
There is a package named mapviz which is a GPS plotter : https://github.com/swri-robotics/mapviz
This issue should be closed ?

**Comment by dirk-thomas** [comment]
@vincentrou Good point.

Also if anyone would like to work on a rqt plugin it doesn't have to be added to this repo anyway. I will close this ticket since it is not more then an idea at this point.
