### ISSUE TITLE
Does not subscribe saved topic if it does not exist yet.

### ISSUE THREAD

**Issue by cyborg-x1** [ros-visualization/rqt_common_plugins#430]
When starting rqt with an image view, the image view does not subscribe its previously saved topic, if it does not exist already. 

Example: 
You start your rqt with Gazebo in a launchfile and another node outputing a video stream in a separate launchfile. You select the topic of this node and save the perspective to launch it later with the first launchfile. You start the launchfile for Gazebo, then the outputing node -> topic is not subscribed by image view. You have to click reload and select the topic again.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_image_view#2
