### ISSUE TITLE
rqt_reconfigure not displaying any param 

### ISSUE THREAD

**Issue by fw-timku** [ros-visualization/rqt_common_plugins#435]
Ubuntu 16.04
Realsense R200 camera

Hi all, I am trying to change the realsense r200 camera settings (lr_gain, lr_exposure etc.) in the r200_params file located in the realsense_camera/cfg folder. I did launch the camera driver through the rgbd nodelet and after which I type the following command 'rosrun rqt_reconfigure rqt_reconfigure' to launch the rqt reconfig window.  However, there is nothing shown in the window. Anyone knows what is the problem?

![rqt](https://cloud.githubusercontent.com/assets/20330769/23244392/c42bf398-f9bf-11e6-9843-d43be712e3e6.png)

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_reconfigure#4
