### ISSUE TITLE
rqt_reconfigure resize disabled with qt5

### ISSUE THREAD

**Issue by nxdefiant** [ros-visualization/rqt_common_plugins#450]
In kinetic the rqt_reconfigure GUI does not allow resize between the left and the right column. This is problematic for e.g. reconfigure params with middle to longer text and reduces the overall usability.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_reconfigure#5

@cottsay I couldn't assign you to the new ticket. Can you please do that yourself. Sorry for the inconvenience.
