### ISSUE TITLE
Include rqt_tf_tree as a common plugin?

### ISSUE THREAD

**Issue by ruffsl** [ros-visualization/rqt_common_plugins#458]
Could we include rqt_tf_tree as a common plugin?

https://github.com/ros-visualization/rqt_tf_tree

 Seems like visualizing tf trees is equivalently common to visualizing graphs or topic messages.

**Comment by dirk-thomas** [comment]
`rqt_tf_tree` is part of the [rqt_robot_plugins](https://github.com/ros-visualization/rqt_robot_plugins/blob/c472f4bebf8d1f0ce81bf074b037936acfc1d656/package.xml#L43) metapackage already which seem to be the more appropriate place.
