### ISSUE TITLE
Display issues with Windows build of rqt_bag gui

### ISSUE THREAD

**Issue by alexinnovap** [ros-visualization/rqt_common_plugins#467]
Hi there, I have just installed ros on my windows 10 system following the official [documentation ](http://wiki.ros.org/Installation/Windows) and I used rqt_bag for GUI purposes. However it seems like the GUI does not have the ability to play or pause the rosbags. Here is an example of the GUI.
![image](https://github.com/ros-visualization/rqt_common_plugins/assets/137399425/f5c6d89a-94f1-487a-8a3e-6063b7ddb981)

If anyone could help me it would be greatly appreciated,

Alex

**Comment by MatthijsBurgh** [comment]
Wrong repo, open an issue in the `rqt_bag` repo
