### ISSUE TITLE
rqt_reconfigure) to be capable of showing only certain parameters

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_common_plugins#49]
In the cases where the users know that the parameters they need to interact with, loading the parameters of all available nodes might just drop the usability. Either or all of the following is useful:
1. [ ] Save the nodes selected in the previous run.
2. [ ] Allow the developers who make `rqt` plugin that depends on `rqt_reconfigure` to pre-select certain nodes

Particularly, I now start having an impression that the majority of the `reconfigure` users might already know which nodes & parameters they need.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_reconfigure#2
