### ISSUE TITLE
(rqt_launch) Only shows .launch files in the folder with the name "launch" 

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_common_plugins#50]
Currently hardcoded [here](https://github.com/ros-visualization/rqt_common_plugins/blob/groovy-devel/rqt_launch/src/rqt_launch/launch_widget.py#L139). Roughly speaking, only 80% of .launch files existing in my filesystem are covered with this rule.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_launch#2
