### ISSUE TITLE
(rqt launch) Launch plugin does not show command lines

### ISSUE THREAD

**Issue by acornacorn** [ros-visualization/rqt_common_plugins#52]
It would be very useful if the full command line for each node (including absolute pathname) is shown in a copy/paste-able field.  This would allow all the other nodes to be launched (by clicking their run buttons) and the node in question to be run by copy-pasting the command line to a terminal.

WHY: this is useful for running one node in debugger (gdb).   Also useful to see the console output of just the one node in its own terminal window.  Also useful to modify (or add) some arguments on the command line

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_launch#3
