### ISSUE TITLE
(rqt launch) nodes do not show up (at first)

### ISSUE THREAD

**Issue by acornacorn** [ros-visualization/rqt_common_plugins#53]
When I first start the RQT launch plugin, no nodes show up.  I see the dotted tree lines on the left where the 2 nodes should be, but no information about the nodes.  If I click on a different launch file and then click back to the original launch file then eventually I see the information about the nodes.

With some launch files, only some of the nodes show up.  For example, run rqt, add the launch plugin, and set the package to pr2_moveit_config.  The first launch file is demo.launch.  I see slots (dotted lines) for 5 nodes, but only the first 2 (static transform publisher and joint state publisher) show up.  Click on a different launch file (same problem).  Then click on demo.launch again.  Now all 5 nodes show up.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_launch#4
