### ISSUE TITLE
rqt_graph should allow a user to pan the graph at all scales

### ISSUE THREAD

**Issue by jbohren** [ros-visualization/rqt_common_plugins#65]
rqt_graph is frustrating to use with large graphs since it prevents the user from panning the graph when it fits in the frame. This means that in order to zoom in on a given part of the graph, the user must first zoom into the middle  of the graph, and then pan repeatedly to get to some other region. Note that in rxgraph, you can pan to arbitrary locations at any scale.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_graph#1
