### ISSUE TITLE
trajectory plotter 

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_common_plugins#69]
Discussed [here](http://answers.ros.org/question/58907/has-anyone-written-a-trajectory-plotting-tool/)

**Comment by dirk-thomas** [comment]
Since the ticket is only about the idea of a new plugin I will close it.

**Comment by 130s** [comment]
[More recent discussion](http://discourse.ros.org/t/joint-state-visualization/405) (may not be exactly the same though).
