### ISSUE TITLE
rqt_bag: point clouds in rqt_bag

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt_common_plugins#7]
Now that we have the new Point Cloud Library (PCL), it would be great if you could store a cloud to disk by clicking on the some pop up associated with point clouds

To download a rxbag plugin to display point clouds see the trac ticket
  https://code.ros.org/trac/ros/ticket/2525

change history from trac (copy pasted on Jan 8 2013):
Changed 3 years ago by tfield 

status changed from new to assigned
milestone ROS 1.1 deleted
Sure, that shouldn't be difficult. Can you suggest a good format to dump them to disk?

Changed 3 years ago by tfield 

I'm hazarding a guess that pcl's PCD format is what you want. Is that correct?

Changed 3 years ago by tfield 

status changed from assigned to closed
resolution set to wontfix
Assuming this is no longer required.

Changed 22 months ago by jcorrea 

status changed from closed to reopened
resolution wontfix deleted
Although PCD is the format to save point cloud provided by PCL library, rxbag lacks the ability so save, or view, point clouds. It would be very desirable to have such feature present.

Changed 22 months ago by tfield 

This is possible. I wrote code recently to serialize PointCloud2 messages in Python. Theoretically, wxPython includes PyOpenGL but I'd need to check how good it is and its cross-platform support.

Changed 22 months ago by jcorrea 

Maybe using VTK for displaying? I may give it a try, but after next week, right now I don't have much time left.

For serializing, I think the best approach would be to try and use PCL, as they already have saving to PCD files.

Changed 22 months ago by tfield 

No need to pull in a huge framework like VTK to display point clouds - it's very simple to write a shader to do that.

Also, no need to use PCL - I've already implemented PointCloud2 serialization natively in Python. As far as I'm aware, PCL doesn't have Python bindings anyway.

Changed 10 months ago by tfield 

owner changed from tfield to gerkey
status changed from reopened to new
Changed 6 months ago by jcorrea

attachment rxbag_pointcloud_plugin.tar.bz2   added
RxBag? plugin to display pointclouds

Changed 6 months ago by jcorrea 

I've attached a plugin for RXBAG that displays pointclouds. It uses matplotlib and probably is not the most optimum approach.

Changed 4 minutes ago by ablasdel 

status changed from new to closed
resolution set to duplicate
The replacement to rxbag in groovy is rqt_bag. It is a port of rxbag and has almost the same plugin api. Please see the github ticket created for this issue here for further information:

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_bag#1
