### ISSUE TITLE
rqt_marble) missing minimum functionalities

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_common_plugins#73]
- [ ] show current pose (GPS coords, facing direction) of a robot
 - User can specify the image of robot marker (preset icons, user's image). Marker system from `RViz`' can be used.
 - If the current position is available, system disables "input start position" feature.
- [ ] Configurable refresh rate
- [ ] Accommodate multiple robots. This might not be straightforward, because `Marble` might not support some of the necessary functions.
 - [ ] I/F to input start & goal points for robots
 - [ ] I/F to accept current positions of multiple robots (`Marble` might support this).

**Comment by dirk-thomas** [comment]
Since the package `rqt_marble` is not being worked on and is in an unusable state I will close this ticket with the label `wontfix` and also remove the package from the repository. If there is interest to continue to work in this package please move the code to a separate repository.

**Comment by dirk-thomas** [comment]
Please see the referenced commit to get to the removed source code of the package.

**Comment by trainman419** [comment]
It looks like the marble_plugin, which rqt_marble was copied from, has seen some continued development: https://github.com/TobiasBaer/marble_plugin
