### ISSUE TITLE
rqt_launch) what happens when switching one .launch file to another, and come back?

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_common_plugins#78]
Behavior not defined for the following case:
1. Nodes are started for `foo.launch`
2. Switch to `bar.launch`. Do whatever for it (nodes from `foo.launch` are still running).
3. Switch back to `foo.launch`.

Currently at 3, the running status of `foo.launch` is not maintained.

I think running multiple instances for the same nodes from the same `.launch` might be possible usecase.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_launch#9
