### ISSUE TITLE
rqt_launch) some processes not stopped by stop button

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_common_plugins#79]
To reproduce, open `demo.launch` in `pr2_moveit_config` pkg on `rqt_launch`. Then open another arbitrary .launch file and open back to `demo.launch` (these are due to issue #53). Click `Start All`. Then click stop buttons for all nodes. Not all but some processes still remain.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_launch#10
