### ISSUE TITLE
rqt_graph) Bring back node information

### ISSUE THREAD

**Issue by dirk-thomas** [ros-visualization/rqt_common_plugins#87]
Moving issue fom rqt opened by @dpsolomon:

Part of what made rxgraph so useful was the node information (pubs, subs, services, and active connections) that was readily available all in one spot. Yes, I know the information is still available via rosnode, but a very useful enhancement to rqt_graph would be to bring back the node information in the sidebar.

**Comment by kunaltyagi** [comment]
@dirk-thomas The publishers and subscribers are visible (via highlighting), on mouse hover. How about adding the msg type to the rqt_graph info? I can begin working on it if no one else is.

**Comment by dirk-thomas** [comment]
Extending the tooltip sounds good to me. It would be great if you can provide a PR for this idea.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_graph#2
