### ISSUE TITLE
rqt_math: plugin to perform math expressions on topics/fields

### ISSUE THREAD

**Issue by dirk-thomas** [ros-visualization/rqt_common_plugins#88]
Moved from rqt opened by @ablasdel:

For example you have a few numeric topics you want to monitor but would prefer to monitor the sum of them.

This becomes even more useful if it allows arbitrary expressions with topics as variables.

**Comment by efernandez** [comment]
FYI http://wiki.ros.org/topic_tools/transform

**Comment by dirk-thomas** [comment]
I will close this since this repo won't contain any plugins anymore. Please consider creating a separate repo for new plugins.
