### ISSUE TITLE
rqt_logger_level: add ability to see what the logging levels are across the system

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt_common_plugins#9]
Preferable in the same rxlogginglevel console.

If it could be a list of "rules" that you've set like the config file. And has an X next to it to remove that rule it would be nice.

Or a tree view with colors would be another option.

migrated from trac ticket 1161:
  https://code.ros.org/trac/ros/ticket/1161

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_logger_level#1
