### ISSUE TITLE
rqt_marble) a feature in a depended library missing on Ubuntu 11.10 Oneiric

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_common_plugins#91]
A necessary header file `Route.h` doesn't get installed on `Oneiric` 64b (I haven't tested with 32b but assume the same) with the latest debian pkg [libmarble-dev 4:4.7.4-0ubuntu0.1](https://launchpad.net/ubuntu/oneiric/amd64/libmarble-dev/4:4.7.4-0ubuntu0.1), which ends up with failure in build.

**Comment by trainman419** [comment]
I think this can be closed because Oneiric is no longer supported.

**Comment by dirk-thomas** [comment]
Agreed, Oneiric is not supported anymore and rqt_marble is not even build anymore (the folder contains a `CATKIN_IGNORE` file). Therefore I will close this ticket as `wontfix`.
